-- [Revenue Streams Analysis]

-- Query 1: Calculate total revenue for each product type and overall revenue
-- This query sums up the revenue generated by Poster, Gloss, and Standard products 
-- from the 'orders' table and also calculates the total revenue.
SELECT 
    SUM(poster_amt_usd) AS poster_total, 
    SUM(gloss_amt_usd) AS gloss_total, 
    SUM(standard_amt_usd) AS standard_total, 
    SUM(total_amt_usd) AS total_revenue
FROM orders o;

-- Query 2: Identify the top 10 accounts contributing the most revenue
-- This query ranks the top 10 accounts by total revenue generated.
-- It calculates the revenue for each product type as well as the total revenue per account.
SELECT 
    a."name" AS account_name, 
    ROUND(SUM(o.poster_amt_usd)) AS poster_total, 
    ROUND(SUM(o.gloss_amt_usd)) AS gloss_total, 
    ROUND(SUM(o.standard_amt_usd)) AS standard_total,
    ROUND(SUM(o.poster_amt_usd + o.gloss_amt_usd + o.standard_amt_usd)) AS total_revenue
FROM accounts a
JOIN orders o 
ON a.id = o.account_id
GROUP BY a."name"
ORDER BY total_revenue DESC 
LIMIT 10;
